### ISSUE TITLE
Adding email address in pop out field

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#401] opened 2015-05-05 09:16 UTC
Tried to show that Freya Greer's email address we have is her mum's and got this message:

Server Error in '/' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /EmailAddress/Create

**Comment by MelHarbour** [comment] 2015-05-05 13:12
I suspect this simply isn't implemented yet.

**Comment by MelHarbour** [comment] 2015-05-05 13:13
Yes, duplicate of #149

**Closed by MelHarbour** 2015-05-05 13:13 UTC
Labels: bug
